check Info.plist for Apple style Java keys
if key :Java is present, parse in apple mode
That’s a better indicator than the location of the Java lib folder in
the app package

diff --git a/src/universalJavaApplicationStub b/src/universalJavaApplicationStub
--- a/src/universalJavaApplicationStub
+++ b/src/universalJavaApplicationStub
@@ -111,8 +111,12 @@ CFBundleName=`/usr/libexec/PlistBuddy -c "print :CFBundleName" "${InfoPlistFile}
 CFBundleIconFile=`/usr/libexec/PlistBuddy -c "print :CFBundleIconFile" "${InfoPlistFile}"`
 
 
-# read Info.plist in Apple style
-if [ -d "${AppleJavaFolder}" ]; then
+# check Info.plist for Apple style Java keys -> if key :Java is present, parse in apple mode
+/usr/libexec/PlistBuddy -c "print :Java" > /dev/null 2>&1 
+exitcode=$?
+
+# read Info.plist in Apple style if exit code returns 0 (true, :Java key is present)
+if [ $exitcode -eq 0 ]; then
 
 	# read the Java WorkingDirectory
 	JVMWorkDir=`/usr/libexec/PlistBuddy -c "print :Java:WorkingDirectory" "${InfoPlistFile}" 2> /dev/null | xargs`
@@ -153,7 +157,7 @@ if [ -d "${AppleJavaFolder}" ]; then
 
 
 # read Info.plist in Oracle style
-elif [ -d "${OracleJavaFolder}" ]; then
+else
 
 	# set Working Directory and Java and Resources folder
 	JavaFolder="${OracleJavaFolder}"
