support for `JVMVersion` plist key // fixes #13

diff --git a/src/universalJavaApplicationStub b/src/universalJavaApplicationStub
--- a/src/universalJavaApplicationStub
+++ b/src/universalJavaApplicationStub
@@ -96,6 +96,8 @@ OracleResourcesFolder="${AppPackageFolder}"/Contents/Resources
 # set path to Info.plist in bundle
 InfoPlistFile="${AppPackageFolder}"/Contents/Info.plist
 
+# set the default JVM Version to a null string
+JVMVersion=""
 
 
 
@@ -171,6 +173,8 @@ if [ $exitcode -eq 0 ]; then
 	# read the JVM Arguments
 	JVMArguments=`/usr/libexec/PlistBuddy -c "print :Java:Arguments" "${InfoPlistFile}" 2> /dev/null | xargs`
 
+    # read the Java version we want to find
+    JVMVersion=`/usr/libexec/PlistBuddy -c "print :Java:JVMVersion" "${InfoPlistFile}" 2> /dev/null | xargs`
 
 # read Info.plist in Oracle style
 else
@@ -211,6 +215,18 @@ fi
 # first check system variable "$JAVA_HOME"
 if [ -n "$JAVA_HOME" ] ; then
 	JAVACMD="$JAVA_HOME/bin/java"
+	
+# check for specified JVMversion in "/usr/libexec/java_home" symlinks
+elif [ ! -z ${JVMVersion} ] && [ -x /usr/libexec/java_home ] ; then
+
+	if /usr/libexec/java_home -F -v ${JVMVersion}; then
+		JAVACMD="`/usr/libexec/java_home -F -v ${JVMVersion} 2> /dev/null`/bin/java"
+	else
+		# display error message with applescript
+		osascript -e "tell application \"System Events\" to display dialog \"ERROR launching '${CFBundleName}'\n\nNo suitable Java version found on your system!\nThis program requires Java ${JVMVersion}\nMake sure you install the required Java version.\" with title \"${CFBundleName}\" buttons {\" OK \"} default button 1 with icon path to resource \"${CFBundleIconFile}\" in bundle (path to me)"
+		# exit with error
+		exit 1
+	fi
 
 # otherwise check "/usr/libexec/java_home" symlinks
 elif [ -x /usr/libexec/java_home ] && [ -d "`/usr/libexec/java_home 2> /dev/null`" ] ; then
